"""initialisation

Revision ID: 78fd990c788a
Revises: 
Create Date: 2022-04-12 14:38:11.594703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78fd990c788a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom_client', sa.String(length=50), nullable=False),
    sa.Column('numero_compte', sa.String(length=50), nullable=False),
    sa.Column('numero_telephone', sa.String(length=20), nullable=False),
    sa.Column('solde', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=300), nullable=False),
    sa.Column('etat', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=50), nullable=False),
    sa.Column('prenom', sa.String(length=50), nullable=False),
    sa.Column('login', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=300), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admin')
    op.drop_table('account')
    # ### end Alembic commands ###
